bitrate: 128000 b/s
sample rate: 44100 Hz 
bit_depth: 16
latency: 4.111 ms 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scapy/utils.py", line 1209, in open
    fdesc = gzip.open(filename, "rb")  # type: _ByteStream
  File "/usr/lib/python3.8/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'tcp-packets.pcap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    packets = rdpcap('tcp-packets.pcap')
  File "/usr/local/lib/python3.8/dist-packages/scapy/utils.py", line 1144, in rdpcap
    with PcapReader(filename) as fdesc:  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/scapy/utils.py", line 1179, in __call__
    filename, fdesc, magic = cls.open(filename)
  File "/usr/local/lib/python3.8/dist-packages/scapy/utils.py", line 1212, in open
    fdesc = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'tcp-packets.pcap'